### ISSUE TITLE
Version-specific resource references

### ISSUE THREAD

**Issue by johngrimes** [aehrc/pathling#216]
It is valid to have a reference from a resource to a specific technical version of another resource (see [Literal References](https://hl7.org/fhir/R4/references.html#literal)).

This change will recognise references of this form, and add the necessary conditions to the join to match the `versionId` within the `meta` element of the target resources.

This functionality will be turned off by default for performance reasons, and will need to be enabled via configuration. The following will be added to the default configuration:

```yaml
pathling:
  query:
    versionSpecificReferencesEnabled: false
```
