### ISSUE TITLE
Logical resource references

### ISSUE THREAD

**Issue by johngrimes** [aehrc/pathling#217]
It is valid to use a logical identifier as a reference to another resource (see [Logical References](https://hl7.org/fhir/R4/references.html#logical)).

This change will recognise references of this form, and add the necessary conditions to the join to match the `identifier` element within target resources.

This functionality will be turned off by default for performance reasons, and will need to be enabled via configuration. The following will be added to the default configuration:

```yaml
pathling:
  query:
    logicalReferencesEnabled: false
```
