### ISSUE TITLE
Join function unsupported but SQL-on-FHIR website says it is?

### ISSUE THREAD

**Issue by brucosper** [aehrc/pathling#2343]
Not sure if the table [here](https://sql-on-fhir.org/extra/impls.html) is just not correct or if I'm doing something wrong.

My expression is just ```item.where(linkId ='something').answer.valueCoding.display.join()```. 

Which gives me this response: 

```
{
    "resourceType": "OperationOutcome",
    "issue": [
        {
            "severity": "error",
            "code": "processing",
            "diagnostics": "Unsupported function: join"
        }
    ]
}
```

I'm running the server on Docker, with this `docker-compose.yml`:
```
version: "3"
services:
  pathling:
    image: aehrc/pathling:7
    ports:
      - 8080:8080
    environment:
      pathling.cors.allowedOrigins: http://localhost:3000

    volumes:
      - pathling:/usr/share/warehouse
      - ndjson:/usr/share/staging
volumes:
  pathling:
    driver: local
```
