### ISSUE TITLE
Throw an error when getting column out of MixedCollection

### ISSUE THREAD

**Issue by johngrimes** [aehrc/pathling#2405]
Currently we return a null column representation from a `MixedCollection`. This manifests on some of the tests, e.g. this passes:

```yaml
    - desc: 'Observation.value without a model'
      expression: 'Observation.value'
      result: []
```

Our implementation is limited in that we can't represent mixed collections in a dataframe, as the column types within Spark do not support this.

I think we should have a new `ColumnRepresentation` called `UnsupportedColumnRepresentation`. Any attempt to retrieve a column will return a descriptive error.
