### ISSUE TITLE
Error for collection that is not a singleton

### ISSUE THREAD

**Issue by johngrimes** [aehrc/pathling#2411]
This fhirpath.js test case currently fails:

```yaml
  - desc: '** error for collection that is not a singleton'
    expression: Functions.collWithNullAndTrue.not()
    error: true
```

```yaml
subject:
  resourceType: Functions
  # ...
  collWithNullAndTrue:
    - null
    - true
```

This indicates a bug with the boolean evaluation of collections logic.

**Comment by johngrimes** [comment]
The exclusion for this test is still in place, and removing it shows that the test is still failing.

**Comment by piotrszul** [comment]
@johngrimes 

This specific example is not about `not()` on non singular collections as this seem to be working fine, see:

```
class BooleanLogicFunctionsDslTest
...
        .testError("stringArray.not()",
            "not() fails on non-boolean non-singular collection")
        
        // not() with boolean arrays
        .testError( "boolArray.not()",
            "not() fails on non-singular boolean collection")
        // not() with complex types
        .testEquals(false, "person.active.not()",
            "not() negates boolean property of complex type")
        .testError("people.active.not()",
            "not() fails on non-singlar boolean computed collection")
```

This is more to do with what 
```
collWithNullAndTrue:
    - null
    - true
```
represents as a collection in our case, when we do not support 'null' elements in collection but rather we 'null' is represented as an absence of the element. I think that in our implementation the colWithNullAndTrue is actually just `{true}` which is singular. 
(we explicitly filter out nulls on traversal - maybe that's not right).

**Comment by johngrimes** [comment]
Ok, I think we can change the type to `wontfix`, remove the issue id and then close this issue.

**Comment by piotrszul** [comment]
Exclusion moved under:
```
    exclude:
      - title: Support for null values within FHIR elements
        type: wontfix
        outcome: failure
```
