### ISSUE TITLE
ofType should be able to filter using FHIRPath types

### ISSUE THREAD

**Issue by johngrimes** [aehrc/pathling#2415]
When supplying a FHIRPath type as the argument to `ofType`, it should be smart enough to map this back to the set of possible FHIR types and filter the collection on this basis.

Spec link: https://hl7.org/fhir/R4/fhirpath.html#types

**Comment by johngrimes** [comment]
Here are some tests that might provide a starting point:

```yaml
tests:
  - desc: 'select string from mixed collection'
    disabled: true
    expression: component.value.ofType(String)
    result: [ 'string' ]
  - desc: 'select integer from mixed collection'
    disabled: true
    expression: component.value.ofType(Integer)
    result: [ 1 ]
  - desc: 'select decimal from mixed collection'
    disabled: true
    expression: component.value.ofType(Decimal)
    result: [ 1.01 ]
  - desc: 'select boolean from mixed collection'
    disabled: true
    expression: component.value.ofType(Boolean)
    result: [ true, false ]


subject:
  resourceType: Observation
  component:
    - valueString: 'string'
    - valueInteger: 1
    - valueDecimal: 1.01
    - valueBoolean: true
    - valueBoolean: false
```
