### ISSUE TITLE
Add support for context to YAML test runner

### ISSUE THREAD

**Issue by johngrimes** [aehrc/pathling#2424]
There is a `context` attribute in the FHIRPath.js tests, looks something like this:

```yaml
tests:
  - 'group: Environment variables':
      - desc: '%context'
        context:  'g1'
        expression: '%context.n1'
        result: [2]

subject:
  n1: 1
  g1:
    n1: 2
```

We don't currently support it and have to exclude this test, it would be good if we could pass it.
