### ISSUE TITLE
Add support for expression maps to YAML test runner

### ISSUE THREAD

**Issue by johngrimes** [aehrc/pathling#2431]
There is an expression -> map feature used within the FHIRPath.js tests, looks something like this:

```yaml
tests:
  - desc: Evaluating expression for a part of a resource
    inputfile: questionnaire-part-example.json
    model: 'r4'
    expression: {base: 'QuestionnaireResponse.item', expression: 'answer.value = 2 year'}
    result:
      - true
```

We don't currently support it and have to exclude this test, it would be good if we could pass it.
